[ids]
* 

[main]

# Keep sending C-A-t
leftcontrol+leftalt+t = C-A-t

# Pressing Left Alt activates the 'alt_nav' layer
leftalt = layer(alt_nav) 

[alt_nav]
# Map the keys in the 'alt_nav' layer to the arrow keys similar to VIM
j = down
h = left
k = up
l = right
